'use strict';

/**
 * perf-baseline.test.js — Slice 3.1 fixture guard.
 *
 * Validates Requirement 4.2 (Hot-Path Hook Performance and Testability) at the
 * baseline-capture step. This slice does NOT add any assertion that could fail
 * the build on perf regression — that lives in slice 3.7 (Lock perf assertions
 * — Ceiling + Headroom). This file's only job is to assert that the committed
 * fixture exists, has the expected shape, and contains positive-finite numbers
 * captured against the legacy (pre-refactor) hook.
 *
 * The fixture is regenerated by running:
 *   node tests/_capture-perf-baseline.js
 *
 * The capture script lives under tests/ with a leading `_` so the
 * `node --test tests/*.test.js` glob ignores it as a test (same convention as
 * `tests/_perf-harness.js`).
 */

const { describe, it } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const FIXTURE_PATH = path.resolve(__dirname, 'fixtures', 'perf-baseline.json');

describe('Perf baseline fixture (Slice 3.1)', () => {
  it('Given a representative 80-char prompt and a representative 500-char prompt, When the legacy hook runs n=100 times each, Then a baseline JSON with p50/p95/mean per fixture is written to tests fixtures', () => {
    assert.ok(
      fs.existsSync(FIXTURE_PATH),
      `expected committed baseline fixture at ${FIXTURE_PATH}; regenerate via 'node tests/_capture-perf-baseline.js'`
    );

    const baseline = JSON.parse(fs.readFileSync(FIXTURE_PATH, 'utf8'));

    // Top-level shape per design slice 3.1 Observable.
    assert.ok(baseline.short80 && typeof baseline.short80 === 'object', 'short80 entry missing');
    assert.ok(baseline.long500 && typeof baseline.long500 === 'object', 'long500 entry missing');
    assert.match(
      baseline.capturedAt,
      /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/,
      'capturedAt must be ISO 8601'
    );
    assert.match(
      baseline.advisorVersion,
      /^\d+\.\d+\.\d+/,
      'advisorVersion must be SemVer-shaped'
    );

    // Per-fixture shape and finiteness.
    for (const key of ['short80', 'long500']) {
      const f = baseline[key];
      for (const stat of ['p50', 'p95', 'mean']) {
        assert.equal(typeof f[stat], 'number', `${key}.${stat} must be a number`);
        assert.ok(Number.isFinite(f[stat]), `${key}.${stat} must be finite`);
        assert.ok(f[stat] > 0, `${key}.${stat} must be positive`);
      }
      // Sanity invariants on percentile ordering.
      assert.ok(
        f.p50 <= f.p95,
        `${key}.p50 (${f.p50}) must be <= ${key}.p95 (${f.p95})`
      );
    }
  });

  it('Given the captured prompts, When their lengths are inspected, Then they fall within ~80 and ~500 char windows', () => {
    if (!fs.existsSync(FIXTURE_PATH)) return; // first test already explains absence
    const baseline = JSON.parse(fs.readFileSync(FIXTURE_PATH, 'utf8'));
    if (typeof baseline.promptShortLength === 'number') {
      assert.ok(
        baseline.promptShortLength >= 70 && baseline.promptShortLength <= 90,
        `promptShortLength=${baseline.promptShortLength} outside 70..90 window`
      );
    }
    if (typeof baseline.promptLongLength === 'number') {
      assert.ok(
        baseline.promptLongLength >= 450 && baseline.promptLongLength <= 550,
        `promptLongLength=${baseline.promptLongLength} outside 450..550 window`
      );
    }
  });
});
